### ISSUE TITLE
JIT failure.

### ISSUE THREAD

**Issue by rdebath** [NightShade256/bfec#3]
I tried to run this: http://www.hevanet.com/cristofd/brainfuck/collatz.b
Your interpreter is giving the correct result, the Jit is not.

You're also limiting it to 30000 cells and 8bits.
This: http://www.hevanet.com/cristofd/brainfuck/impeccable.b needs 59193 cells for the first seven values, others need 32bit or even 64bit cells.

```
$ echo -ne '4123456789\n\0' | bb/bin32/NightShade256-bfec -j collatz.b
1027X

Execution Time: 0s.
$ echo -ne '4123456789\n\0' | bb/bin32/NightShade256-bfec collatz.b
226


Execution Time: 0s.
$
```

**Comment by NightShade256** [comment]
@rdebath 
First of all thanks for opening the issue and reporting it.

1. I now know the problem behind the JIT error and will be patching it very soon.
2. I plan to support bigger tape size and bit size in the future.

Thanks again!

**Comment by NightShade256** [comment]
The latest commit in `master` fixes this issue.

PS. I use your `bitwidth` program heavily to test my implementations!
